### ISSUE TITLE
Refuses to work on ubuntu 17.10

### ISSUE THREAD

**Issue by AlexKrimi** [honix/Pyno#3]
I run Pyno.py using the py3.6 interpreter, it shows me the welcome window with some blocks, but does not allow me to click on any box OR freezes when i click some box. what could be the source of problem?

![2018-04-04 15-57-27](https://user-images.githubusercontent.com/8288487/38308807-e649e336-3820-11e8-8e0c-4f404950752b.png)

**Comment by honix** [comment]
Hi, i have same problem today! The solution is to install oldish version of pyglet. Check updated instructions in readme file.
-------- Исходное сообщение --------От: Alex Krimi <notifications@github.com> Дата: 04.04.18  15:51  (GMT+03:00) Кому: honix/Pyno <Pyno@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [honix/Pyno] Refuses to work on ubuntu 17.10 (#3) 
I run Pyno.py using the py3.6 interpreter, it shows me the welcome window with some blocks, but does not allow me to click on any box OR freezes when i click some box. what could be the problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/honix/Pyno","title":"honix/Pyno","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/honix/Pyno"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Refuses to work on ubuntu 17.10 (#3)"}],"action":{"name":"View Issue","url":"https://github.com/honix/Pyno/issues/3"}}}

**Comment by AlexKrimi** [comment]
A bit better now with pyglet-1.3.0, but still very laggy,
it takes 10 sec to move a box by my drag and then it freezes

UPD: i've deleted the previously auto-created auto-save.pn
and changed line 60 in window.py so it loads ping-pong.pn by default instead of welcome.pn and it works fine as well as for particle.pn, mouse-keyboard.pn and simple graphics.pn

BUT it is still laggy for many_batch_graphics.pn , so i guess the problem is in processing some *.pn files

I've tried to upgrade to pyglet-1.3.1 and run with the ping-pong on startup and it still works fine, so the source was not in the library version

**Comment by AlexKrimi** [comment]
Basically, Pyno window with blocks works ok when it is not the only window

**Comment by honix** [comment]
Yep! If you loaded many pathes, it can slow down the process. Btw for me any patch in examples folder works pretty fast with stable ~60 fps

**Comment by GurePortela** [comment]
Hello!
I'm using pyno to do number theory research, it's really cool, however, I'm not a programmer, so I'm studying python, I'd like to know if you want to make some modules ready for use in the pyno, model library, and I'd like to know if it is possible to change the angle of rotation of the nodes, so they can better be connected, organize the layout.
Seriaq also good button player, pause, stop to control the simulation
wonder of program .... Congrats!
Brazil

**Comment by drtrigon** [comment]
> Seriaq also good button player, pause, stop to control the simulation

I agree on this! Play and Stop are mandatory (I work on this), Pause would be nice. Also general way of process/flow control is needed like: delay/wait, wait for other may be not connected block, loops, etc. (similar to what LabView has)

(Sorry for thread hijacking)

**Comment by GurePortela** [comment]
Ok!

**Comment by GurePortela** [comment]
my simulation number calc
![snap 2018-11-03 at 20 10 40](https://user-images.githubusercontent.com/36675042/47958167-a626ee80-dfa4-11e8-8318-cb2ee6161ff6.png)

**Comment by GurePortela** [comment]
![snap 2018-11-03 at 20 13 59](https://user-images.githubusercontent.com/36675042/47958185-103f9380-dfa5-11e8-8e21-f04b2c47c7a6.png)
![Uploading Snap 2018-11-03 at 20.14.47.png…]()

**Comment by GurePortela** [comment]
![snap 2018-11-03 at 20 14 47](https://user-images.githubusercontent.com/36675042/47958190-1f264600-dfa5-11e8-8a3f-5402841daea0.png)

**Comment by GurePortela** [comment]
I'm using transfer nodes to be able to better organize the layout without those lines all on the screen. So I wish the pin connection line could be directed like an electronic circuit drawing program, or that the nodes could be rotated
google traductor........!

**Comment by honix** [comment]
Wow! Beautiful patches @GurePortela.

**Comment by bilderbuchi** [comment]
Wow, nice! Concerning patch organization and expressivity/architecture of node-based languages, I have always found https://vvvv.org/ to be great to work with, I think one could do worse than using that as a reference.

**Comment by honix** [comment]
Yep! vvvv was my main inspiration of visual languages. They now working hard on VL - interesting new spin of vvvv, more generic and with more powerful abstractions!

I also recommend to check out cables.gl project.

**Comment by honix** [comment]
@AlexKrimi do you still have problem with bad pyno performance? If so reopen this issue please!
