### ISSUE TITLE
Do not redraw each editor frame

### ISSUE THREAD

**Issue by honix** [honix/Pyno#35]
Because of this (CPU usage):

![image](https://user-images.githubusercontent.com/11596541/48796096-c3cbb600-ed0f-11e8-9d16-e4c6844f9022.png)

When user doesn't drag or zoom the canvas, there is no need for full redraw. In this case we only need to redraw elements of field type, as they present real-time data.

**Comment by GurePortela** [comment]
Fields store responses that saturate the system by creating latency. Could you decrease the number of data output sampling fields so that it works as a window, type a display, display?
Assigning you input buttons and an exit button, so it would work as a display for several nodes.
Could the subprocess window be kept active inside the main window?
For what and gain input buttons and output data and be resizable?
