### ISSUE TITLE
why lambda is a filed

### ISSUE THREAD

**Issue by autosquid** [honix/Pyno#4]
I guess node means callable; while field the opposite?

**Comment by honix** [comment]
Yes, nodes is functions. Named functions with some inputs and some outputs.

So, fields can hold any literal value: number, string, array of something, or even lambda. They all objects and can be used as arguments.

Since lambda is really an object, it can be shown up in any part of the program, and then passed anywhere as an argument.

**Comment by autosquid** [comment]
thx, closing it.
