### ISSUE TITLE
Feature request: Add new element that represents a pyno-file

### ISSUE THREAD

**Issue by drtrigon** [honix/Pyno#5]
Currently there are two elements: node and field.

Can you add a third element that represents a pyno-file? That way it would be possible to group complex files/flows into several files or to reuse pyno-files for various purposes. I would propose to use either fields or the open connections of the pyno-file as connections for the new object.

**Comment by honix** [comment]
This is cool idea. Looks like subpatching.
Unluckely i havent much time to do this. Can you try to do?
-------- Исходное сообщение --------От: drtrigon <notifications@github.com> Дата: 22.10.2018  14:07  (GMT+03:00) Кому: honix/Pyno <Pyno@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [honix/Pyno] Feature request: Add new element that represents a pyno-file (#5) 
Currently there are two elements: node and field.
Can you add a third element that represents a pyno-file? That way it would be possible to group complex files/flows into several files or to reuse pyno-files for various purposes. I would propose to use either fields or the open connections of the pyno-file as connections for the new object.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/honix/Pyno","title":"honix/Pyno","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/honix/Pyno"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Feature request: Add new element that represents a pyno-file (#5)"}],"action":{"name":"View Issue","url":"https://github.com/honix/Pyno/issues/5"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/honix/Pyno/issues/5",
"url": "https://github.com/honix/Pyno/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Feature request: Add new element that represents a pyno-file (#5)",
"sections": [
{
"text": "",
"activityTitle": "**drtrigon**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@drtrigon",
"facts": [
{
"name": "Repository: ",
"value": "honix/Pyno"
},
{
"name": "Issue #: ",
"value": 5
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"honix/Pyno\",\n\"issueId\": 5,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"honix/Pyno\",\n\"issueId\": 5\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/honix/Pyno/issues/5"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 399285921\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by drtrigon** [comment]
Thanks for your fast answer. I have the same time restrictions unfortunately. However I had a look at the source code and have to say I could may be add a new (visual) element derived from node.py but I have no clue how to implement the code merging and execution. (sorry!)

**Comment by drtrigon** [comment]
The implementation may have quite some bugs and be hacky - I leave this to you, tell me what you think. I wait for feedback... enjoy! ;)

**Comment by honix** [comment]
Thanks! I will try it on computer in next two days.

**Comment by drtrigon** [comment]
Go for the latest version pushed a clean-up commit.

**Comment by honix** [comment]
Feedback part. I really glad to see activity around pyno! Your investment makes me to refine my interest in this project.

I like the way you implement it. I just done some minor things to make it user friendly.

I want to advance time control panel you just made, by adding "step" button. Step button will execute update just once.

My future plans is to add flow-control concepts to the system. Im ready to discuse the way to do it.

The main goal is to keep system simple and hackable.

**Comment by GurePortela** [comment]
Ficou muito bom,assim como ele falou ter importado a idéia do Icestudio,poderia usar o conceito de ligação desse soft, para facilitar  a modelagem dos fios de ligação entre os nós e campos?
No geral ficou maravilhosso, todavia, precisa aumentar a distancia entre os pinos no no do sub-processo para facilitar a ligação dos fios.
Parabens!!

It was very good, just as he said to have imported the idea of ​​Icestudio, could use the concept of connection of this soft, to facilitate the modeling of the connection wires between the nodes and fields?
Overall it was wonderful, however, you need to increase the distance between the pins in the sub process notch to make it easier to connect the wires.
Congratulations!!
![snap 2018-11-05 at 18 11 04](https://user-images.githubusercontent.com/36675042/48027328-460c8580-e127-11e8-8298-edc39204e046.png)

**Comment by drtrigon** [comment]
Thanks to everybody for all the feedback to this issue and for testing!


> Feedback part. I really glad to see 
> activity around pyno! Your investment 
> makes me to refine my interest in this 
> project.

Cool!! I like to see and use more of pyno! :)

>I like the way you implement it. I just done some minor things to make
>it user friendly.

I just did what was needed and ended up with quite elegant and minimal code changes - I like it too. I think this is and indication that you did a good job with the design of the code!
I hoped for you to "polish" the code, thanks a lot!

>I want to advance time control panel you just made, by adding "step"
>button. Step button will execute update just once.

Would also be my next TODO. Good idea!

>My future plans is to add flow-control concepts to the system. Im ready
>to discuse the way to do it.

I did a first very hack approach in "flow_control_delay.pn" did you see it? This might be a way to go BUT also produces non-trivial side effects: notice 1 field gets updated immediately, the other 2 NOT even though 1 of it should. Think this is related to the nodes list order.

>The main goal is to keep system simple and hackable.

I totally agree! Only this made my contribution possible in the first place!

The size of the element should either by changable by the user or may be better and simpler; adopt with number of inputs and outputs. Second should be fairy simple to implement.

**Comment by drtrigon** [comment]
@honix: Don't know whether you already saw https://github.com/drtrigon/Pyno/commit/d53b4bc11843f3e9b179d4de40ae3adc59fb24f2 it is improving on the sub's name/label displayed and closing pyno. I also had time to finally test the serial pyno (sorry for not doing so before).
